pod 'CocoaAsyncSocket'
pod 'AFNetworking','~> 2.6.0'
pod 'Masonry'
pod 'KVNProgress'
pod 'BaiduMapKit'
pod 'MJExtension'
pod 'SDWebImage'
pod 'RealReachability'
pod 'Pingpp/Alipay'
pod 'Pingpp/Wx'
pod 'Pingpp/UnionPay'
pod 'Pingpp/ApplePay'
pod 'UMengSocial'
